name: C++ Linting

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/setup-node

    - name: Install C++ compiler and clang-tidy
      run: |
        sudo apt-get update
        sudo apt-get install -y g++ clang-tidy

    - name: Run Linting
      run: |
        clang-tidy --version
        clang-tidy ./src/**/*.cpp -- -std=c++17
